FROM python:3.11-slim
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ARG INSTALL_COMMAND=i-prod
WORKDIR /code

COPY ./pyproject.toml /code/

RUN pip install pdm && \
    python -m pdm ${INSTALL_COMMAND}

COPY ./client /code/client/