version: '3.9'
services:

  server:
    build:
      context: .
      args:
        - INSTALL_COMMAND=i-dev
    container_name: server
    command: pdm run server
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: on-failure
    volumes:
      - ./app/:/code/app
      - ./app/logs:/code/logs
    depends_on:
      - postgres
    tty: true

  client:
    build:
      dockerfile: Dockerfile-client
      args:
        - INSTALL_COMMAND=i-client
    container_name: client
    command: pdm run client
    ports:
      - "8002:8002"
    env_file:
      - .env
    restart: on-failure
    tty: true
    depends_on:
      - server

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - app-postgres-db:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    tty: true


volumes:
  app-postgres-db:

